name: hiclik_app
description: Hiçlik - Turkish quotes app with TTS capabilities.
publish_to: 'none' 
version: 1.0.2+3

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_tts: ^3.8.3  # For text-to-speech functionality
  audioplayers: ^5.1.0  # For background audio
  shared_preferences: ^2.2.1  # For storing app state
  provider: ^6.0.5  # For state management
  animated_text_kit: ^4.2.2  # For text animations
  flutter_spinkit: ^5.2.0  # For loading animations

  flutter_native_splash: any
  http: any
  path_provider: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1  # Add this package

# This part is critical - it must be at this level in the YAML, not indented
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo.png"  # Same image for foreground
  adaptive_icon_background: "#000000"  # Black background
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
    - assets/audio/

flutter_native_splash:
  color: "#000000"
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    icon_background_color: "#000000"    