class QuotesProvider {
  static List<String> getQuotes() {
    return [
      "Hiçlik, her şeyin başladığı yerdir.",
      "Sessizlik, hiçliğin sesi gibidir.",
      "Düşünceler sustuğunda, hiçlik ortaya çıkar.",
      "Varlık, hiçliğe dokunduğunda anlam kazanır.",
      "Hiçlik, zihnin en derin boşluğudur.",
      "Yokluk, bazen huzurun ta kendisidir.",
      "Hiçliğin içinde benliğini bulursun.",
      "Sessizliğin içinden gelen ses, hiçliğin yankısıdır.",
      "Hiçlik, her şeyden önce gelir.",
      "Zihin boşaldığında, hiçlik gelir.",
      "Sonsuzluk hiçlikten doğar.",
      "Her şey, bir hiçlik kıvılcımıyla başlar.",
      "Boşluk, varlığın sahnesidir.",
      "Hiçlik, varoluşun zeminidir.",
      "Anlam, hiçlikte çözülür.",
      "Bazen hiçbir şey, her şeyden daha çok şey anlatır.",
      "Karanlık, hiçliğin bir yüzüdür.",
      "Hiçlik seni yutar, sonra yeniden doğurur.",
      "Zaman bile hiçliğe boyun eğer.",
      "Hiçlik, tüm cevapların içinde saklıdır.",
      "Bir nefes kadar yakın, ama görünmez: Hiçlik.",
      "Sonsuzluk, hiçliğin tekrar eden aynasıdır.",
      "Varlığın gölgesi, hiçliktir.",
      "Hiçlik seni korkutmasın, o senin özündür.",
      "Yoklukla yüzleşmek, kendini tanımaktır.",
      "Kalabalıklar içinde bile hiçliği hissedersin.",
      "En derin huzur, hiçliktedir.",
      "Hiçlik, varoluşun sıfır noktasıdır.",
      "Hiçlik, her şeyi barındıran boşluktur.",
      "Düşünme durduğunda, hiçlik konuşmaya başlar.",
      "Sessizlik, hiçliğe açılan bir kapıdır.",
      "Hiçlikte bir sonsuzluk gizlidir.",
      "Kendini bulmak için önce hiçliğe gitmelisin.",
      "Varlık, hiçlik olmadan eksiktir.",
      "Hiçlik bir son değil, bir başlangıçtır.",
      "İçindeki boşluk, hiçliğe açılan bir geçittir.",
      "Hiçlik, zihnin derin uykusudur.",
      "Boşluk, sonsuzun kapısıdır.",
      "Her şey, hiçlikle dengelenir.",
      "Hiçliği kabul etmek, özgürlüktür.",
      "Sözler bittiğinde, hiçlik başlar.",
      "Hiçlik, tüm anlamların kaynağıdır.",
      "Var olmamak da bir varoluş biçimidir.",
      "Yokluk, bazen en büyük varlıktır.",
      "Hiçlik, tüm düşünceleri eriten bir sessizliktir.",
      "Hiçlik, içinde huzur taşıyan bir boşluktur.",
      "Duyular sustuğunda, hiçliği duyarsın.",
      "Gözlerini kapattığında bile görebilirsin hiçliği.",
      "Hiçlik, zamanın ötesindedir.",
      "Varlık, hiçlikle dengede kalır.",
      "Her şey geçer, hiçlik kalır.",
      "Hiçlik, sonsuz olasılıkların ana rahmidir.",
      "Yolun sonunda seni bekleyen şey, hiçliktir.",
      "Hiçlik seni sarmaladığında, gerçek sen ortaya çıkar.",
      "Hiçliğin kokusu bile yoktur, ama hissedersin.",
      "Bir an dur ve hiçliği hisset.",
      "Hiçliğe açılan her kapı, kendine açılır.",
      "Hiçlik seni kendine yaklaştırır.",
      "Zihin sustuğunda, ruh hiçlikle dans eder.",
      "Hiçlik, varlığa en yakın şeydir.",
      "Düşünceler yavaşladığında, hiçlik belirir.",
      "Hiçliğin huzurunda kal.",
      "Her şeyin özü, hiçliktir.",
      "Hiçlik sana hiçbir şey vermez ama her şeyi sağlar.",
      "Hiçlik bir boşluk değil, bir deneyimdir.",
      "Hiçlikte kaybolmak, kendini bulmaktır.",
      "Hiçlik, tüm sorulara cevaptır.",
      "Sonsuzluk, hiçliğin gölgesinde büyür.",
      "Hiçlik bir sessizlik değil, bir bilinç halidir.",
      "Zaman, hiçliğe yenik düşer.",
      "Hiçlik seni değiştirmez, seni hatırlatır.",
      "Hiçlik içinde yankılanan benliğindir.",
      "Varoluş bir kıvılcım, hiçlik sonsuzluktur.",
      "Hiçlik seni yargılamaz, sarar.",
      "Boşluk korkutucu değildir, o bir aynadır.",
      "Hiçlik, bir adım ötede bekliyor.",
      "Hiçlik, seni sen yapar.",
      "Zihin boşaldığında, farkındalık başlar.",
      "Hiçlik, en saf sadeliktir.",
      "Her şeyin sonunda kalan tek şey: hiçlik.",
      "Hiçlik içinde özgürleşirsin.",
      "Hiçlik seni duyar ama konuşmaz.",
      "Hiçlik, sözlerin ötesinde bir varlıktır.",
      "Hiçlik yok etmez, arındırır.",
      "Hiçlik, varoluşun en sakin kıyısıdır.",
      "Hiçlik, zamanın sustuğu andır.",
      "Hiçlik seni tüketmez, dinlendirir.",
      "Hiçlik seni çağırır, fısıltıyla.",
      "Hiçlik seni durdurmaz, fark ettirir.",
      "Hiçlik bir boşluk değil, bir alan sunar.",
      "Hiçlik seni yalnız bırakmaz, seninledir.",
      "Sessizlik uzarsa, hiçlik gelir.",
      "Hiçlik seni unutturmaz, tanımlar.",
      "Hiçlik bir cevap değil, sorudur.",
      "Hiçlikte yaşamak, farkındalıkla yaşamak demektir.",
      "Hiçlik zamanla yarışmaz.",
      "Hiçlik varlığını ispatlamaz, yaşatır.",
      "Hiçlik ve varlık, aynı aynanın iki yüzüdür.",
      "Hiçlik seni silmez, berraklaştırır.",
      "Hiçlik seni boğmaz, nefes verir.",
    ];
  }
}